package com.example.kaone.ui

object KpopData {
    val cityDistricts = mapOf(
        "基隆市" to listOf("仁愛區", "信義區", "中正區", "中山區", "安樂區", "暖暖區", "七堵區"),
        "台北市" to listOf("中正區", "大同區", "中山區", "松山區", "大安區", "萬華區", "信義區", "士林區", "北投區", "內湖區", "南港區", "文山區"),
        "新北市" to listOf("板橋區", "三重區", "中和區", "永和區", "新莊區", "新店區", "土城區", "蘆洲區", "樹林區", "汐止區", "三峽區", "淡水區", "鶯歌區", "五股區", "泰山區", "林口區", "深坑區", "石碇區", "坪林區", "三芝區", "石門區", "八里區", "平溪區", "雙溪區", "貢寮區", "金山區", "萬里區", "烏來區", "瑞芳區"),
        "桃園市" to listOf("桃園區", "中壢區", "平鎮區", "八德區", "楊梅區", "蘆竹區", "大溪區", "龍潭區", "龜山區", "大園區", "觀音區", "新屋區", "復興區"),
        "新竹市" to listOf("東區", "北區", "香山區"),
        "新竹縣" to listOf("竹北市", "竹東鎮", "新埔鎮", "關西鎮", "湖口鄉", "新豐鄉", "芎林鄉", "橫山鄉", "北埔鄉", "寶山鄉", "峨眉鄉", "尖石鄉", "五峰鄉"),
        "苗栗縣" to listOf("苗栗市", "頭份市", "竹南鎮", "後龍鎮", "通霄鎮", "苑裡鎮", "卓蘭鎮", "造橋鄉", "西湖鄉", "頭屋鄉", "公館鄉", "銅鑼鄉", "三義鄉", "大湖鄉", "獅潭鄉", "三灣鄉", "南庄鄉", "泰安鄉"),
        "南投縣" to listOf("南投市", "埔里鎮", "草屯鎮", "竹山鎮", "集集鎮", "名間鄉", "鹿谷鄉", "中寮鄉", "魚池鄉", "國姓鄉", "水里鄉", "信義鄉", "仁愛鄉"),
        "台中市" to listOf("中區", "東區", "南區", "西區", "北區", "北屯區", "西屯區", "南屯區", "太平區", "大里區", "霧峰區", "烏日區", "豐原區", "后里區", "石岡區", "東勢區", "和平區", "新社區", "潭子區", "大雅區", "神岡區", "大肚區", "沙鹿區", "龍井區", "梧棲區", "清水區", "大甲區", "外埔區", "大安區"),
        "彰化縣" to listOf("彰化市", "員林市", "和美鎮", "鹿港鎮", "溪湖鎮", "二林鎮", "田中鎮", "北斗鎮", "花壇鄉", "芬園鄉", "大村鄉", "永靖鄉", "伸港鄉", "線西鄉", "福興鄉", "秀水鄉", "埔心鄉", "埔鹽鄉", "大城鄉", "芳苑鄉", "竹塘鄉", "溪州鄉", "埤頭鄉", "二水鄉", "田尾鄉", "社頭鄉"),
        "雲林縣" to listOf("斗六市", "斗南鎮", "虎尾鎮", "西螺鎮", "土庫鎮", "北港鎮", "古坑鄉", "大埤鄉", "莿桐鄉", "林內鄉", "二崙鄉", "崙背鄉", "麥寮鄉", "東勢鄉", "褒忠鄉", "台西鄉", "元長鄉", "四湖鄉", "口湖鄉", "水林鄉"),
        "嘉義市" to listOf("東區", "西區"),
        "嘉義縣" to listOf("太保市", "朴子市", "布袋鎮", "大林鎮", "民雄鄉", "溪口鄉", "新港鄉", "六腳鄉", "東石鄉", "義竹鄉", "鹿草鄉", "水上鄉", "中埔鄉", "竹崎鄉", "梅山鄉", "番路鄉", "大埔鄉", "阿里山鄉"),
        "台南市" to listOf("中西區", "東區", "南區", "北區", "安平區", "安南區", "永康區", "歸仁區", "新化區", "左鎮區", "玉井區", "楠西區", "南化區", "仁德區", "關廟區", "龍崎區", "官田區", "麻豆區", "佳里區", "西港區", "七股區", "將軍區", "學甲區", "北門區", "新營區", "後壁區", "白河區", "東山區", "六甲區", "下營區", "柳營區", "鹽水區", "善化區", "大內區", "山上區", "新市區", "安定區"),
        "高雄市" to listOf("楠梓區", "左營區", "鼓山區", "三民區", "苓雅區", "新興區", "前金區", "鹽埕區", "前鎮區", "旗津區", "小港區", "鳳山區", "林園區", "大寮區", "大樹區", "大社區", "仁武區", "鳥松區", "岡山區", "橋頭區", "燕巢區", "田寮區", "阿蓮區", "路竹區", "湖內區", "茄萣區", "永安區", "彌陀區", "梓官區", "旗山區", "美濃區", "六龜區", "甲仙區", "杉林區", "內門區", "茂林區", "桃源區", "那瑪夏區"),
        "屏東縣" to listOf("屏東市", "潮州鎮", "東港鎮", "恆春鎮", "萬丹鄉", "長治鄉", "麟洛鄉", "九如鄉", "里港鄉", "高樹鄉", "鹽埔鄉", "內埔鄉", "竹田鄉", "萬巒鄉", "新埤鄉", "枋寮鄉", "新園鄉", "崁頂鄉", "林邊鄉", "南州鄉", "佳冬鄉", "琉球鄉", "車城鄉", "滿州鄉", "枋山鄉", "三地門鄉", "霧台鄉", "瑪家鄉", "泰武鄉", "來義鄉", "春日鄉", "獅子鄉", "牡丹鄉"),
        "宜蘭縣" to listOf("宜蘭市", "羅東鎮", "蘇澳鎮", "頭城鎮", "礁溪鄉", "壯圍鄉", "員山鄉", "冬山鄉", "五結鄉", "三星鄉", "大同鄉", "南澳鄉"),
        "花蓮縣" to listOf("花蓮市", "鳳林鎮", "玉里鎮", "新城鄉", "吉安鄉", "壽豐鄉", "光復鄉", "豐濱鄉", "瑞穗鄉", "富里鄉", "秀林鄉", "萬榮鄉", "卓溪鄉"),
        "台東縣" to listOf("台東市", "成功鎮", "關山鎮", "卑南鄉", "鹿野鄉", "池上鄉", "東河鄉", "長濱鄉", "太麻里鄉", "大武鄉", "綠島鄉", "海端鄉", "延平鄉", "金峰鄉", "達仁鄉", "蘭嶼鄉"),
        "澎湖縣" to listOf("馬公市", "湖西鄉", "白沙鄉", "西嶼鄉", "望安鄉", "七美鄉"),
        "金門縣" to listOf("金城鎮", "金湖鎮", "金沙鎮", "金寧鄉", "烈嶼鄉", "烏坵鄉"),
        "連江縣" to listOf("南竿鄉", "北竿鄉", "莒光鄉", "東引鄉")
    )

    val groupMembersData = mapOf(
        "&TEAM" to listOf("K|古賀祐大", "FUMA|村田風雅", "NICHOLAS|王奕翔", "EJ|邊義州", "YUMA|中耒田悠真", "JO|朝倉穣", "HARUA|重田美琉愛", "TAKI|高山浬希", "MAKI|宏田力"),
        "aespa" to listOf("Karina|劉知珉", "Giselle|內永枝利", "Winter|金旼炡", "Ningning|寧藝卓"),
        "AOA" to listOf("Park Cho A|朴草娥","Shin Ji Min|申智珉","Seo Yu Na|徐酉奈","Seo You Kyung|徐有慶","Shin Hye Jeong|申惠晶","Kwon Min A|權珉娥","Kim Seol Hyun|金雪炫","Im Do Hwa|林到婲"),
        "AHOF" to listOf("Steven", "Seo Jeongwoo|徐廷雨", "Cha Woongki|車雄基", "Zhang Shuaibo|張帥博", "Park Han|朴翰", "JL", "Park Juwon|朴周元", "Chih en|志恩", "Daisuke|宮崎大輔"),
        "ALLDAY PROJECT" to listOf("Annie|文徐允", "Tarzzan|李埰源", "Bailey|石有真", "Woochan|趙旴燦", "Youngseo|李榮書"),
        "ALPHA DRIVE ONE|ALD1" to listOf("Junseo|金俊抒", "Arno|張家豪", "Leo|李理悟", "Geonwoo|金虔佑", "Sangwon|李相沅", "Xinlong|賀鑫隆", "Anxin|周安信", "Sanghyeon|鄭相炫"),
        "ARTMS" to listOf("JinSoul|眞率","HaSeul|夏瑟","Kim Lip","HeeJin|姬振","Choerry"),
        "Apink" to listOf("Chorong|朴初瓏", "Bomi|尹普美", "Eunji|鄭恩地", "Namjoo|金南珠", "Hayoung|吳夏榮"),
        "ARrC" to listOf("Kien|阮忠堅", "Hyunmin|朴炫彬", "Choihan|崔翰", "Andy|奧田敏英", "Rioto|金子凜音", "Doha|金道河","Jibeen|李智彬"),
        "ASTRO" to listOf("MJ|金明俊", "Jinjin|朴真佑", "Eunwoo|車銀優", "Moonbin|文彬", "Rocky|朴慜赫", "Sanha|尹產賀"),
        "AB6IX" to listOf("jeon Woong|田雄","Kim Dong Hyun|金東賢","Park Woo Jin|朴佑鎭","Lee Dae Hwi|李大輝"),
        "A.C.E" to listOf("Lee Ji Ham|李沚諴","Wow|金世潤","Park Jun Hee|朴晙喜","Kim Byeong Kwan|金柄官","Kang Yu Chan|康裕瓚"),
        "ATEEZ" to listOf("Seonghwa|朴星化", "Hongjoong|金弘中",  "Yunho|丁潤浩", "Yeosang|姜呂尚", "San|崔傘", "Mingi|宋旼琦", "Wooyoung|鄭友榮", "Jongho|崔鍾浩"),
        "AMPERS&ONE" to listOf("Kamden|羅斗彬","Brian|何廷威","Jiho|崔智鎬","Siyun|尹恃奫","Kyrell|崔英","Mackiah|李業俊","SEUNGMO|金承模"),
        "ADYA" to listOf("Yeonsu|柳沇秀","Seowon|鄭曙元","Sena|林汭拏","Chaeeun|尹彩銀","Seungchae|趙升彩"),
        "AtHeart" to listOf("Michi|藤原道","Arin|李雅琳","Katelyn|陳琪仁","Bome|李春","Seohyeon|文諝炫","Nahyun|金奈炫"),
        "ASC2NT" to listOf("Karam|朴賢哲","Jay|全志奐","Reon|趙宰潤","Kyle|金祥燮","Hyowon|李効原"),
        "BLACKPINK" to listOf("Jisoo|金智秀", "Jennie|金珍妮", "Rosé|朴彩英", "Lisa|拉莉莎"),
        "BSS|夫碩順" to listOf("Hoshi|權順榮", "DK|李碩珉", "Seungkwan|夫勝寬"),
        "BABYMONSTER" to listOf("Ruka|河井瑠花", "Pharita|查恩雅", "Asa|榎並杏紗", "Ahyeon|鄭雅譞", "Rami|申厦藍", "Rora|李茶仁", "Chiquita|莉拉查"),
        "Billlie" to listOf("Moonsua|文秀雅", "Suhyeon|金秀炫", "Haram|金하람", "Tsuki|福富つき", "Sheon|金秀娟", "Siyoon|金始玧", "Haruna|大里春菜"),
        "BOYNEXTDOOR" to listOf("Sungho|朴聖淏", "Riwoo|李常赫", "Jaehyun|明宰鉉", "Taesan|漢東旼", "Leehan|金桐凇", "Woonhak|金雲鶴"),
        "BTS|防彈少年團" to listOf("RM|金南俊", "Jin|金碩珍", "Suga|閔玧其", "J-Hope|鄭號錫", "Jimin|朴智旻", "V|金泰亨", "Jungkook|田柾國"),
        "BIGBANG" to listOf("Taeyang|太陽", "G-Dragon|權志龍", "Daesung|大聲"),
        "CLASS:y" to listOf("Hyungseo|明炯瑞", "Chaewon|尹彩源", "Hyeju|洪慧朱", "Riwon|金利源", "Jimin|元知敏", "Boeun|朴甫檼", "Seonyou|金璇猷"),
        "CLOSE YOUR EYES" to listOf("Minwook|全珉稶", "Jingxiang|馬靖翔", "Yeojun|張汝遵", "Sungmin|金成旼", "Seungho|宋承浩", "Sakurada Kenshin|櫻田健真", "Kyoungbae|徐竟培"),
        "CNBLUE" to listOf("Yonghwa|鄭容和", "Minhyuk|姜敏赫", "Jungshin|李正信"),
        "CORTIS" to listOf("James|趙雨凡", "Juhoon|金主訓", "Martin|馬丁", "Seonghyeon|嚴成玹", "Keonho|安乾鎬"),
        "CRAVITY" to listOf("Serim|朴世琳", "Allen|馬蒔權", "Jungmo|具廷謨", "Woobin|徐宇璸", "Wonjin|咸元進", "Minhee|姜珉熙", "Hyeongjun|宋刑準", "Taeyoung|金太榮", "Seongmin|安性珉"),
        "DAYCHILD" to listOf("Intae|千仁泰","Siwoo|咸勝完","K|金建","Eden|黃載浩","Yejong|全業鐘","Sung Hoon|尹升勳"),
        "Dreamcatcher" to listOf("JiU|祉攸", "SuA|秀雅", "SiYeon|始娟", "HanDong|韓東", "YooHyeon|裕賢", "DaMi|多美", "GaHyeon|佳泫"),
        "DRIPPIN" to listOf("Hyeop|李協","Yunseong|黃允省","Changuk|周昌煜","Dongyun|金東玧","Minseo|金敏緒","Junho|車俊昊"),
        "ENHYPEN" to listOf("Heeseung|李羲承", "Jay|朴綜星", "Jake|沈載倫", "Sunghoon|朴成訓", "Sunoo|金善禹", "Jungwon|梁禎元", "Ni-ki|西村力"),
        "EXO" to listOf("Suho|金俊勉", "Xiumin|金珉錫", "Lay|張藝興", "Baekhyun|邊伯賢", "Chen|金鍾大", "Chanyeol|朴燦烈", "D.O.||都敬秀", "Kai|金鍾仁", "Sehun|吳世勳"),
        "E'LAST" to listOf("Choi In|崔仁","Seung Yeop|昇燁","Rano|邊龍燮","Baek Gyeul|白潔","Romin|崔榮敏","Won Hyuk|元赫","Won Jun|沅俊","Ye Jun|藝俊"),
        "EXID" to listOf("Solji|許率智","LE|安孝珍","Hani|安喜延","Hyelin|徐慧潾","Jeonghwa|朴正花"),
        "EPEX" to listOf("WISH","MU|徐烱慜","A-MIN|曺敏宇","BAEKSEUNG|金賢佑","AYDEN|權叡俊","YEWANG|徐藝汪","JEFF|李宰昊"),
        "fromis_9" to listOf("Hayoung|宋河英", "Jiwon|朴池原", "Chaeyoung|李彩煐", "Nagyung|李娜炅", "Jiheon|白知憲"),
        "G-Dragon" to listOf("G-Dragon|權志龍"),
        "Girls' Generation|少女時代" to listOf("Taeyeon|金太妍", "Sunny|李純揆", "Tiffany|黃美永", "Hyoyun|金孝淵", "Yuri|權俞利", "Sooyoung|崔秀榮", "Yoona|林潤娥", "Seohyun|徐朱玄"),
        "GFRIEND" to listOf("Sowon|金韶情", "Yerin|鄭睿隣", "Eunha|銀河", "Yuju|崔裕娜", "SinB|信飛", "Umji|嚴智"),
        "GOT the beat" to listOf("BoA|寶兒", "Taeyeon|金太妍", "Hyoyun|金孝淵", "Seulgi|康瑟琪", "Wendy|孫承完", "Karina|劉知珉", "Winter|金旼炡"),
        "GOT7" to listOf("Mark|段宜恩", "Jay B|林在範", "Jackson｜王嘉爾", "Jinyoung|朴真榮", "Youngjae|崔榮宰", "BamBam|恭比穆格·普瓦古爾", "Yugyeom|金有謙"),
        "Highlight" to listOf("Yoon Dujun|尹斗俊","Yang Yoseop|梁耀燮","Lee Gikwang|李起光","Son Dongwoon|孫東雲"),
        "Heart2Hearts" to listOf("Carmen", "Jiwoo|崔志宇", "Yuha|柳河覽", "Stella|金多絢", "Juun|金主恩", "A-Na|盧惟娜", "Ian|鄭以安", "Ye-On|金奈延"),
        "Hoshi X Woozi|HxW" to listOf("Hoshi|權順榮","Woozi|李知勳"),
        "I-DLE" to listOf("Miyeon|曺薇娟", "Minnie|米妮", "Soyeon|田小娟", "Yuqi|宋雨琦", "Shuhua|葉舒華"),
        "IDID" to listOf("Yonghoon|張容熏", "Minjae|金民財", "Wonbin|朴元彬", "Yoochan|秋喩纂", "Seonghyeon|朴省炫", "Junhyuk|白峻赫", "Semin|鄭勢潣"),
        "ITZY" to listOf("Yeji|黃禮志", "Lia|崔智壽", "Ryujin|申留眞", "Chaeryeong|李彩領", "Yuna|申有娜"),
        "IVE" to listOf("Wonyoung|張員瑛", "Yujin|安兪真", "Rei|直井怜", "Gaeul|金秋天", "Liz|金智媛", "Leeseo|李瑞"),
        "izna" to listOf("Mai|富岡茉衣", "Jeemin|房智玟", "Koko|楢井瑚々", "Sarang|柳莎朗", "Jungeun|崔庭銀", "Saebi|鄭勢譬"),
        "IZ*ONE" to listOf("Eunbi|權恩妃", "Sakura|宮脇咲良", "Hyewon|姜惠元", "Yena|崔叡娜", "Chaeyeon|李彩演", "Chaewon|金采源", "Minju|金玟周", "Nako|矢吹奈子", "Hitomi|本田仁美", "Yuri|曺柔理", "Yujin|安俞真", "Wonyoung|張員瑛"),
        "KiiiKiii" to listOf("Leesol|李修旻", "Sui|李守彬", "Jiyu|徐知裕", "Haum|郭河音", "Kya|朴祉禹"),
        "KISS OF LIFE" to listOf("Julie", "Natty", "Belle", "Haneul"),
        "LE SSERAFIM" to listOf("Sakura|宮脇咲良", "Chaewon|金采源", "Yunjin|許允眞", "Kazuha|中村一葉", "Eunchae|洪恩採"),
        "LIGHTSUM" to listOf("Sangah|尹相雅", "Chowon|韓霄瑗", "Nayoung|金娜英", "Hina|長井陽菜", "Juhyeon|李珠賢", "Yujeong|李宥姃"),
        "LNGSHOT" to listOf("OHYUL|權五律","RYUL|金栗","WOOJIN|鄭宇津","LOUIS|林路易"),
        "MAMAMOO" to listOf("Solar|頌樂", "Moonbyul|玟星", "Wheein|輝人", "Hwasa|華莎"),
        "MAMAMOO+" to listOf("Solar|頌樂", "Moonbyul|玟星"),
        "MEOVV" to listOf("Ella", "Gawon|李嘉元", "Sooin|金粹仁", "Anna|田中杏奈", "Narin|羅潾"),
        "MONSTA X" to listOf("Shownu|孫賢祐", "Minhyuk|李玟赫", "Kihyun|柳基現", "Hyungwon|蔡亨願", "Joohoney|李周憲", "I.M|任創均"),
        "NCT 127" to listOf("Taeyong|李泰容", "Johnny|徐煐淏", "Yuta|中本悠太", "Doyoung|道英", "Jaehyun|在玹", "Jungwoo|金廷祐", "Mark|李敏形", "Haechan|楷燦", "Winwin|昀昀"),
        "NCT DOJAEJUNG" to listOf("Doyoung|道英", "Jaehyun|在玹", "Jungwoo|廷祐"),
        "NCT DREAM" to listOf("Mark|李敏形", "Renjun|黃仁俊", "Jeno|李帝努", "Haechan|李楷燦", "Jaemin|羅渽民", "Chenle|鍾辰樂", "Jisung|朴志晟"),
        "NCT WISH" to listOf("Sion|吳是溫", "Riku|前田陸", "Yushi|得能勇志", "Jaehee|栽禧", "Ryo|廣瀨遼", "Sakuya|藤永咲哉"),
        "NewJeans" to listOf("Minji|金玟池", "Hanni|范玉欣", "Danielle|牟智慧", "Haerin|姜諧潾", "Hyein|李惠仁"),
        "NEXZ" to listOf("Yu|富安悠", "Tomoya|植村朋哉", "Haru|井上陽", "So Geon|蘇建", "Seita|河嶋星太", "Hyui|小森優陽", "Yuki|西山裕貴"),
        "NiziU" to listOf("Mako|山口真子", "Rio|花橋梨緒", "Maya|勝村摩耶", "Riku|大江梨久", "Ayaka|新井彩花", "Mayuka|小合麻由佳", "Rima|橫井里茉", "Miihi|鈴野未光", "Nina|牧野仁菜"),
        "NMIXX" to listOf("Lily|朴珍", "Haewon|吳海嫄", "Sullyoon|薛侖娥", "Bae|裴真率", "Jiwoo|金智佑", "Kyujin|張圭真"),
        "N.Flying" to listOf("Lee Seung Hyub|李承協","Cha Hun|車勳","Kim Jae Hyun|金宰鉉","Yoo Hwe Seung|柳會勝","Seo Dong Sung|徐東成"),
        "P1Harmony" to listOf("Keeho|尹起昊", "Theo|崔太洋", "Jiung|崔智雄", "Intak|黃寅拓", "Soul|白翔太", "Jongseob|金鐘燮"),
        "PURPLE K!SS" to listOf("Goeun|羅高恩", "Dosie|張恩誠", "Ireh|曹敍榮", "Yuki|毛利小雪", "Chaein|李採映", "Swan|朴秀珍"),
        "QWER" to listOf("Chodan|曹玉珠", "Magenta|馬真熙", "Hina|張娜英", "Siyeon|李始燕"),
        "Red Velvet" to listOf("Irene|裴柱現", "Seulgi|康瑟琪", "Wendy|孫承完", "Joy|朴秀英", "Yeri|金藝琳"),
        "Red Velvet - IRENE & SEULGI" to listOf("Irene|裴柱現", "Seulgi|康瑟琪"),
        "RIIZE" to listOf("Shotaro|大崎將太郎", "Eunseok|宋恩奭", "Sungchan|鄭成燦", "Wonbin|朴元彬", "Sohee|李炤熙", "Anton|李燦榮"),
        "SAY MY NAME" to listOf("Hitomi|本田仁美", "Shuie|楊舒萌", "Mei|寺田萌衣", "Kanny", "Soha|鄭玟河", "Dohee|金導熙", "Junhwi|徐俊輝", "Seung週|尹升注"),
        "SEVENTEEN" to listOf("S.Coups|崔勝哲", "Jeonghan|尹淨漢", "Joshua|洪知秀", "Jun|文俊輝", "Hoshi|權順榮", "Wonwoo|全圓佑", "Woozi|李知勳", "The8|徐明浩", "Mingyu|金珉奎", "DK|李碩珉", "Seungkwan|夫勝寛", "Vernon|崔瀚率", "Dino|李燦"),
        "SF9" to listOf("Inseong|金仁誠", "Youngbin|金永彬", "Jaeyoon|李在允", "Dawon|達淵", "Zuho|朱豪", "Taeyang|柳太陽", "Hwiyoung|輝映", "Chani|澯熙"),
        "STAYC" to listOf("Sumin|秀珉", "Sieun|蒔恩", "Isa|璦莎", "Seeun|勢銀", "Yoon|潤", "J|婕怡"),
        "Stray Kids" to listOf("Bang Chan|方燦", "Lee Know|李旻浩", "Changbin|徐彰彬", "Hyunjin|黃鉉辰", "Han|韓知城", "Felix|李龍馥", "Seungmin|金昇玟", "I.N|梁精寅"),
        "SuperM" to listOf("Taemin|李泰民", "Baekhyun|邊伯賢", "Kai|金鍾仁", "Taeyong|李泰容", "Ten", "Lucas|黃旭熙", "Mark|李敏形"),
        "TEMPEST" to listOf("Hanbin|韓彬", "Hyeongseop|炯燮", "Hyuk|本奕", "Eunchan|恩燦", "LEW|義雄", "Taerae|太徠"),
        "THE BOYZ" to listOf("Sangyeon|李上淵", "Jacob|裵俊英", "Younghoon|金泳勳", "Jaehyun|李在賢", "Juyeon|李柱延", "Kevin|文炯書", "New|崔燦喜", "Q|池昌珉", "Sunwoo|金善旴", "Eric|孫英宰"),
        "TOMORROW X TOGETHER|TXT" to listOf("Soobin|崔秀彬", "Yeonjun|崔然竣", "Beomgyu|崔杋圭", "Taehyun|姜太顯", "Hueningkai|休寧凱"),
        "tripleS" to listOf("Yooyeon|金琉然", "Mayu|髙麗 真友", "Xinyu|周心語", "Nakyoung|金拏炅", "Sohyun|朴昭玹", "Dahyun|徐多賢", "Nien|許念慈", "Seoyeon|尹舒姸", "JiYeon|池諝娫", "Kotone|嘉味元 琴音", "ChaeYeon|金采嬿", "YuBin|孔裕彬", "Jiwoo|李知禹", "Kaede|山田楓", "Shion|朴示溫", "Lynn|川上凜", "Sullin", "HyeRin|鄭慧潾", "ChaeWon|金采湲", "HaYeon|丁夏妍", "SooMmn|金秀珉", "Yeonji|郭姸知", "Joobin|周彬", "Seoah|鄭楷潾"),
        "TWICE" to listOf("Nayeon|林娜璉", "Jeongyeon|俞定延", "Momo|平井桃", "Sana|湊崎紗夏", "Jihyo|朴志效", "Mina|名井南", "Dahyun|金多賢", "Chaeyoung|孫彩瑛", "Tzuyu|周子瑜"),
        "TWS" to listOf("Shinyu|申惟", "Dohoon|崔道勳", "Youngjae|崔英宰", "Hanjin|韓振", "Jihoon|韓志訓", "Kyungmin|李炅"),
        "UNIS" to listOf("Hyeonju|陳賢珠","Nana|江角奈奈","Gehlee","Kotoko|河田琴子","Yunha|方鈗河","Elisia","Yoona|吳潤妸","Seowon|林恕願"),
        "VERIVERY" to listOf("Dongheon|李東憲", "Hoyoung|裴浩榮", "Minchan|洪慜撰", "Gyehyeon|趙啓賢", "Yeonho|朱延浩", "Yongseung|金勇勝", "Kangmin|柳岡旻"),
        "VIVIZ" to listOf("Eunha|銀河", "SinB|信飛", "Umji|嚴智"),
        "WANNA ONE" to listOf("Jisung|尹智聖", "Sungwoon|河成雲", "Minhyun|黃旼炫", "Seongwu|邕聖祐", "Jaehwan|金在煥", "Daniel|姜丹尼爾", "Jihoon|朴志訓", "Woojin|朴佑鎭", "Jinyoung|裴珍映", "Daehwi|李大輝", "Kuanlin|賴冠霖"),
        "WayV" to listOf("Kun|錢錕", "Ten", "Winwin|昀昀", "Xiaojun|肖俊", "Hendery|黃冠亨", "Yangyang|劉揚揚"),
        "WEi" to listOf("Daehyeon|張大賢", "Donghan|金東漢", "Yongha|劉勇河", "Yohan|金曜漢", "Seokhwa|姜錫華", "Junseo|金俊抒"),
        "WJSN|宇宙少女" to listOf("Seola|雪娥", "Bona|苞娜", "Exy|秋昭貞", "Soobin|秀斌", "Eunseo|恩熙", "Yeoreum|夏天", "Dayoung|多榮", "Yeonjung|延靜"),
        "XG" to listOf("CHISA|近藤千彩","HINATA|宗原日向","JURIN|淺谷珠琳","HARVEY|哈維瑛美","JURIA|上田純利亞","MAYA|河地瑪雅","COCONA|秋山心響"),
        "xikers" to listOf("Minjae|金玟縡","Junmin|朴埈民","Sumin|崔粹珉","Jinsik|咸珍植","Hyunwoo|崔峴瑀","Junghoon|金正勳","Seeun|朴世殷","Yujun|鄭有埈","Hunter|朴巘攄","Yechan|李預讚"),
        "Xdinary Heroes" to listOf("Gun-il|具建逸","Jungsu|金正洙","Gaon|郭智碩","O.de|吳承珉","Jun Han|韓亨準","Jooyeon|李周演"),
        "ZEROBASEONE|ZB1" to listOf("Jiwoong|金地雄", "Zhang Hao|章昊", "Hanbin|成韓彬", "Matthew|石馬修", "Taerae|金泰來", "Ricky|沈泉銳", "Gyuvin|金奎彬", "Gunwook|朴乾旭", "Yujin|韓維辰")
    )

    val groupAlbumData = mapOf(
        "&TEAM" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "aespa" to listOf("Black Mamba", "Forever", "Next Level", "Savage", "Dreams Come True", "2021 Winter SMTOWN:SMCU EXPRESS", "Season's greetings 2022","Life's Too Short","Girls","2022 Fan Meeting <MY Synk>","Everland X SMtown（愛寶樂園）","2nd Anniversary","Pink Christmas 2022","2022 SMCU PALACE","Season's greetings 2023","VALENTINE'S CAFE","Come to MY illusion","Oh! Caendy Pocket","MY WORLD","MY-J fanclub","Better Things","aespa Exhibition #potd","Drama","Armageddon","Hot Mess","SYNK : PARALLEL LINE","Whiplash","Dirty Work","Rich Man","SYNK : aeXIS LINE"),
        "AOA" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "AHOF" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ALLDAY PROJECT" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ALPHA DRIVE ONE|ALD1" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ARTMS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Apink" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ARrC" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ASTRO" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "AB6IX" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "A.C.E" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ATEEZ" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "AMPERS&ONE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ADYA" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "AtHeart" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ASC2NT" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "BLACKPINK" to listOf("As If It's Your Last","Square Up","Kill This Love","How You Like That","THE ALBUM","BORN PINK","DEADLINE","Jennie《SOLO》","Rosé《-R-》","Lisa《LALISA》","Jisoo《ME》","Lisa 《Alter Ego》","Jennie 《Ruby》","Rosé 《rosie》","Jisoo 《Amortage》","日輯《Blackpink》","日輯《Blackpink In Your Area》","日輯《Kill This Love》","日輯《THE ALBUM》","日版《Blackpink 2019-2020 World Tour In Your Area - Tokyo Dome》","《THE SHOW》 Live CD","《The Girls》 (Blackpink The Game OST)"),
        "BSS|夫碩順" to listOf("SECOND WIND","Just Do It (거침없이)","SEVENTEEN 《CARAT LAND》","SEVENTEEN 《Follow》 演唱會","SEVENTEEN 《Right Here》 演唱會","Oreo 聯名","Cass Beer 代言","Bananain  聯名","Music Bank「打歌禮/放送卡」","Inkigayo「打歌禮/放送卡」"),
        "BABYMONSTER" to listOf("BABYMONS7ER","DRIP","H.I.T.S"),
        "Billlie" to listOf("the Billage of perception: chapter one","the collective soul and unconscious: snowy night","the collective soul and unconscious: chapter one","the Billage of perception: chapter two","the Billage of perception: chapter three","the collective soul and unconscious: chapter zero","the Billage of perception: chapter four","the Billage of perception: finale / transition","日輯《GingaMingaYo (the strange world) - Japanese ver.》","日輯《Knock-on Effect》"),
        "BOYNEXTDOOR" to listOf("WHO!","WHY..","HOW?","19.99","AND?","20.00","日輯《AND,》"),
        "BTS|防彈少年團" to listOf("2 Cool 4 Skool","O!RUL8,2?","Skool Luv Affair","Dark & Wild","花樣年華 Pt.1 & Pt.2","花樣年華 Young Forever","WINGS","You Never Walk Alone","Love Yourself 承 'Her'","Love Yourself 轉 'Tear'","Love Yourself 結 'Answer'","Map of the Soul: Persona","Map of the Soul: 7","BE","Butter","Proof","Jin (The Astronaut)","Jin (Happy)","RM (Indigo)","RM (Right Place, Wrong Person)","J-Hope (Jack In The Box)","J-Hope (HOPE ON THE STREET VOL.1)","Suga (D-DAY)","Jimin (FACE)","Jimin (MUSE)","V (Layover)","Jungkook (GOLDEN)","2014日輯《No More Dream》","2014日輯《Boy In Luv》","2014日輯《Danger》","2015日輯《Wake Up》","2015日輯《For You》","2015日輯《I NEED U》","2016日輯《RUN》","2016日輯《YOUTH》","2017日輯《血、汗、淚 (Blood Sweat & Tears)》","2017日輯《MIC Drop/DNA/Crystal Snow》","2018日輯《Face Yourself》","2018日輯《Fake Love/Airplane pt.2》","2019日輯《Lights/Boy With Luv》","2020日輯《Map of the Soul: 7 ~The Journey~》","2021日輯《BTS, THE BEST》","Memories 2014","Memories 2015","Memories 2016","Memories 2017","Memories 2018","Memories 2019","Memories 2020","Memories 2021","Memories 2019+2020 藍光版","Memories 《BTS 7 Moments》","2014: 1st Muster [MUSTE]","2016: 2nd Muster [ZIP+CODE : 17520]","2016: 3rd Muster [ARMY.ZIP+]","2018: 4th Muster [Happy Ever After]","2019: 5th Muster [Magic Shop]","2021: 6th Muster [Sowoozoo]","2014-2015: The Red Bullet (World Tour)","2015: Wake Up: Open Your Eyes (World Tour)","2016: 花樣年華 On Stage / Epilogue (World Tour)","2017: THE WINGS TOUR / The Final (World Tour)","2018-2019: Love Yourself / Speak Yourself (World Tour)","2020-2022: Permission To Dance On Stage (World Tour)","Summer Package (2014-2019)","Bon Voyage (2016-2019): 第一季至第四季","Winter Package (2020-2021)","In the SOOP (2020-2022): 第一季、第二季","Exhibition 展覽: 2015: 《Butterfly Dream》","Exhibition 展覽: 2018: 《24/7 = Serendipity》","Exhibition 展覽: 2022: 《Proof》","Exhibition 展覽: 2024: 《Hybe Insight》系列展覽卡","Puma 聯名","SK Telecom (電信公司)聯名","Mediheal 面膜 (整套小卡組)聯名","VT Cosmetics (化妝品)聯名","Lotte Duty Free (樂天免稅店)聯名","Samsung Galaxy S20+ (紫色限定版)聯名","Baskin Robbins (冰淇淋)聯名","McDonald's (麥當勞 The BTS Meal 聯名卡)聯名","Coway (飲水機/空氣清淨機)聯名","Celine 聯名","Dior 聯名","Valentino 聯名","Tiffany & Co. 聯名"),
        "BIGBANG" to listOf("Bigbang Vol.1","Always","Hot Issue","Stand Up","Tonight","Special Edition","Alive","Still Alive","《MADE》 系列:M","《MADE》 系列:A","《MADE》 系列:D","《MADE》 系列:E","MADE (THE FULL ALBUM)","Still Life","日輯《BIGBANG 2》","日輯《Alive -Monster Edition-》","日輯《The Best of BIGBANG 2006-2014》","日輯《MADE SERIES》","G-DRAGON (GD)《One of a Kind》","G-DRAGON (GD)《COUP D'ETAT》","G-DRAGON (GD)《權志龍 (Kwon Ji Yong)》","G-DRAGON (GD)《Übermensch》","TAEYANG (太陽)《Rise》","TAEYANG (太陽)《White Night》","TAEYANG (太陽)《Down to Earth》","TAEYANG (太陽)《Quintessence》","DAESUNG (大聲)日輯 《D'scover》","DAESUNG (大聲)日輯 《D'slove》","DAESUNG (大聲)日輯 《D-Day》","DAESUNG (大聲)《D's WAVE》","T.O.P《Doom Dada》","SEUNGRI (勝利)《Let's Talk About Love》","SEUNGRI (勝利)《The Great Seungri》"),
        "CLASS:y" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "CLOSE YOUR EYES" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "CNBLUE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "CORTIS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "CRAVITY" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "DAYCHILD" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Dreamcatcher" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "DRIPPIN" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ENHYPEN" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "EXO" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "E'LAST" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "EXID" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "EPEX" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "fromis_9" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "G-Dragon" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Girls' Generation|少女時代" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "GFRIEND" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "GOT the beat" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "GOT7" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Highlight" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Heart2Hearts" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Hoshi X Woozi|HxW" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "I-DLE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "IDID" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ITZY" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "IVE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "izna" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "IZ*ONE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "KiiiKiii" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "KISS OF LIFE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "LE SSERAFIM" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "LIGHTSUM" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "LNGSHOT" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "MAMAMOO" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "MAMAMOO+" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "MEOVV" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "MONSTA X" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NCT 127" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NCT DOJAEJUNG" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NCT DREAM" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NCT WISH" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NewJeans" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NEXZ" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NiziU" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "NMIXX" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "N.Flying" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "P1Harmony" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "PURPLE K!SS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "QWER" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Red Velvet" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Red Velvet - IRENE & SEULGI" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "RIIZE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "SAY MY NAME" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "SEVENTEEN" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "SF9" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "STAYC" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Stray Kids" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "SuperM" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "TEMPEST" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "THE BOYZ" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "TOMORROW X TOGETHER|TXT" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "tripleS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "TWICE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "TWS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "UNIS" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "VERIVERY" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "VIVIZ" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "WANNA ONE" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "WayV" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "WEi" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "WJSN|宇宙少女" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "XG" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "xikers" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "Xdinary Heroes" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","",""),
        "ZEROBASEONE|ZB1" to listOf("","","","","","","","","","","","","","","","","","","","","","","","","","")
    )
}
